export default {
    messages: {
        TCP_NO_CONNECTION: 'TCP_NO_CONNECTION',
        TCP_TIMEOUT: 'TCP_TIMEOUT',
        CRC32: 'CRC32',
        AES: 'AES',
        INPUT_SURFACE_NAME: 'INPUT_SURFACE_NAME',
        QR_FALSE: 'QR_FALSE',
        QR_FALSE_MASTER_REQ: 'QR_FALSE_MASTER_REQ',
        ADD_SURFACE_SURFACE_CURRENT_NOT_FOUND: 'ADD_SURFACE_SURFACE_CURRENT_NOT_FOUND', // 1
        ADD_SURFACE_WIFI_UNREACHABLE_SURFACE: 'ADD_SURFACE_WIFI_UNREACHABLE_SURFACE',  //1
        ADD_SURFACE_WIFI_UNREACHABLE_CURRENT: 'ADD_SURFACE_WIFI_UNREACHABLE_CURRENT', //1
        ADD_SURFACE_SURFACE_PASSWORD: 'ADD_SURFACE_SURFACE_PASSWORD', //1
        ADD_SURFACE_SURFACE_TIMEOUT: 'ADD_SURFACE_SURFACE_TIMEOUT', //1
        ADD_SURFACE_SET_ADAPTER: 'ADD_SURFACE_SET_ADAPTER',
        ADD_SURFACE_TCP_NO_CONNECTION: 'ADD_SURFACE_TCP_NO_CONNECTION', //1
        ADD_SURFACE_TCP_TIMEOUT: 'ADD_SURFACE_TCP_TIMEOUT',
        ADD_SURFACE_CRC32: 'ADD_SURFACE_CRC32',
        ADD_SURFACE_AES: 'ADD_SURFACE_AES',
        ADD_SURFACE_REMOVE: 'ADD_SURFACE_REMOVE',
        ADD_SURFACE_SURFACE_KNOWN: 'ADD_SURFACE_SURFACE_KNOWN',
        ADD_SURFACE_SURFACE_KNOWN_UPGRADE: 'ADD_SURFACE_SURFACE_KNOWN_UPGRADE',
        ADD_SURFACE_SURFACE_UNKNOWN_UPGRADE: 'ADD_SURFACE_SURFACE_UNKNOWN_UPGRADE',
        LOGIN_USER_CREATE_EXISTS: 'LOGIN_USER_CREATE_EXISTS',
        LOGIN_RESET_NOT_FOUND: 'LOGIN_RESET_NOT_FOUND',
        LOGIN_FORGOT_NOT_FOUND: 'LOGIN_FORGOT_NOT_FOUND',
        LOGIN_FAILED: 'LOGIN_FAILED',
        HTTP_409: 'HTTP_409',
        HTTP_404: 'HTTP_404',
        HTTP_400: 'HTTP_400',
        HTTP_403: 'HTTP_403',
        HTTP_DEFAULT: 'HTTP_DEFAULT',
        SURFACE_DELETE_CONFIRM: 'SURFACE_DELETE_CONFIRM',
        SURFACE_RESET_CONFIRM: 'SURFACE_RESET_CONFIRM',
        SURFACE_DELETE_AFTER: 'SURFACE_DELETE_AFTER',
        SURFACE_RESET_AFTER: 'SURFACE_RESET_AFTER',
        UPDATE_FIRMWARE: 'UPDATE_FIRMWARE',
        NOT_CURRENT: 'NOT_CURRENT',
        GROUP_DELETE: 'GROUP_DELETE',
        GROUP_CANT_EDIT: 'GROUP_CANT_EDIT',
        RESET_PASSWORD_PRE: 'RESET_PASSWORD_PRE',
        RESET_PASSWORD: 'RESET_PASSWORD',
        HELP_SCENES: 'HELP_SCENES',
        HELP_AUTO: 'HELP_AUTO',
        HELP_SURFACES: 'HELP_SURFACES',
        HELP_SCENECONFIG: 'HELP_SCENECONFIG',
        HELP_PLAYLISTS: 'HELP_PLAYLISTS',
    }
}